# Generated by Django 3.1.8 on 2021-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210618_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='profile_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
