# Generated by Django 3.1.8 on 2021-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210722_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='about',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
