# Generated by Django 3.1.8 on 2021-07-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_auto_20210709_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.post'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='groups.post'),
        ),
    ]
